version: '3.9'

services:
  frontend:
    container_name: svelte_for_chads
    image: nginx:alpine
    restart: always
    volumes:
      - ./configs:/etc/nginx/conf.d
      - ./build:/project
    ports:
      - 3333:80
